-- Cities table
CREATE DATABASE IF NOT EXISTS hbtn_0c_usa;
USE hbtn_0c_usa;
CREATE TABLE IF NOT EXISTS cities (id INT PRIMARY KEY AUTO_INCREMENT, state_id INT FOREIGN KEY REFERENCES states(id) NOT NULL, name VARCAHR(256) NOT NULL);
